### ISSUE TITLE
"mas upgrade" command

### ISSUE THREAD

**Issue by frdmn** [argon/mas#1]
Instead of:

```shell
❯ mas outdated
747648890 Telegram (1.90)
557168941 Tweetbot for Twitter (2.1)

❯ mas install 747648890
==> Downloading Telegram
==> Installed Telegram

❯ mas install 557168941
==> Downloading Tweetbot for Twitter
==> Installed Tweetbot for Twitter
```

just something like ...

```shell
❯ mas upgrade
The following applications are outdated: Telegram (1.90), Tweetbot for Twitter (2.1)
==> Downloading Telegram
==> Installed Telegram
==> Downloading Tweetbot for Twitter
==> Installed Tweetbot for Twitter
```

**Comment by argon** [comment]
This is added in v1.0.2

**Comment by frdmn** [comment]
Thanks a lot.

Now I can try to implement it in @mattly's DSL, bork

https://github.com/mattly/bork

Von meinem iPhone gesendet

**Comment by argon** [comment]
Great! Please do let me know if you have any problems, this was a difficult feature to test.

**Comment by mattly** [comment]
OOOH. Thanks @frdmn for letting me know about this program, I can now swap out my horrible hacky implementation at https://github.com/mattly/bork/blob/master/types/macstore.sh with bindings for mas.
