### ISSUE TITLE
Allow `mas install` to accept multiple arguments

### ISSUE THREAD

**Issue by danyalaytekin** [argon/mas#28]
This would allow multiple applications to be installed more concisely when setting up a new machine.  The syntax is offered by other package managers like Homebrew and RubyGems.

Current syntax: `mas install 1234 && mas install 2345 && mas install 3456`
Suggested syntax: `mas install 1234 2345 3456`

**Comment by argon** [comment]
Neat idea.

**Comment by merqurio** [comment]
please! this would be awesome ! super useful for environment setups !

**Comment by argon** [comment]
Released in v1.2.1

**Comment by argon** [comment]
A bit pre-emptive there. This should be in the next release.
