### ISSUE TITLE
`install` should check if app is already installed.

### ISSUE THREAD

**Issue by reitermarkus** [argon/mas#31]
I don't know if this is a bug or if it's just not implemented yet. When I run `mas install 12345678`, it starts downloading immediately, even if the app is already installed.

**Comment by argon** [comment]
The current implementation isn't considered a bug as it serves the purpose of updating also.

Perhaps it would be a good idea to offer a flag to force reinstallation (the current behaviour) and by default do nothing if it's already installed and up-to-date. Is that what you had in mind?

**Comment by reitermarkus** [comment]
Exactly, if my app is up-to-date, I don't want to have to reinstall it. A `--force` flag would be a good solution to this.

As for `install` also updating the app, I don't really have an opinion if this should solely be done in the `upgrade` command.

**Comment by argon** [comment]
There is no simple way to implement an `upgrade` command as `install` does both by default, hence the current behaviour. I will look at implementing a `--force` flag, thanks for the input.

**Comment by reitermarkus** [comment]
I don't know if how I imagine this would work is inefficient, but wouldn't this work?

`install`

1. Check if app is installed.
2. If it isn't, install it.

 `upgrade`

1. Check if app is installed.
2. If it is, upgrade it.

**Comment by ckelner** [comment]
I concur - I'm building automated install scripts for myself to bootstrap a workstation that I would like to be idempotent

**Comment by edrozenberg** [comment]
+1 if app is already installed, it shouldn't again download and install it each time the install command is invoked on the app id.

**Comment by kdbertel** [comment]
+1. This behavior surprised me, because it is inconsistent with `brew`.

**Comment by argon** [comment]
This has landed in master now

**Comment by ckelner** [comment]
Awesome!  Thanks @argon
