### ISSUE TITLE
Project has not been migrated to Swift 3

### ISSUE THREAD

**Issue by Spamm3r** [argon/mas#33]
==> Downloading https://github.com/argon/mas/archive/v1.2.0.tar.gz
Already downloaded: /Users/kaczmarzyktomasz/Library/Caches/Homebrew/mas-1.2.0.tar.gz
==> gem install bundler
==> script/bootstrap
==> xcodebuild -project mas-cli.xcodeproj -scheme mas-cli -configuration Release
Last 15 lines from /Users/kaczmarzyktomasz/Library/Logs/Homebrew/mas/03.xcodebuild:
        guard let updates = updateController.availableUpdates() where updates.count > 0 else {
                            ^
                                            ?
/tmp/mas-20160623-1006-1p3ul22/mas-1.2.0/mas-cli/Commands/Version.swift:15:21: error: 'NSBundle' has been renamed to 'Bundle'
        let plist = NSBundle.mainBundle().infoDictionary
                    ^~~~~~~~
                    Bundle

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.

Fix this asap

**Comment by argon** [comment]
A fix for this has been merged but will not be released until I have made some further improvements. If you wish to use `mas` on Sierra please download a binary directly from GitHub or compile the `master` branch directly.

**Comment by MikeMcQuaid** [comment]
@argon Would be 🆒 if you could have a new tagged release (1.2.1?) before Sierra comes out as the current version doesn't compile there and your Homebrew-using users will likely start complaining. Thanks!

**Comment by MikeMcQuaid** [comment]
(note: the current `master` works fine).

**Comment by argon** [comment]
v1.2.1 has been released

**Comment by MikeMcQuaid** [comment]
Thanks @argon!
