### ISSUE TITLE
Fails to build on Swift 2.x because thoughtbot/Curry's master is on Swift 3 already

### ISSUE THREAD

**Issue by rodionovd** [argon/mas#39]
Hi @argon, thanks for the great project ❤️

I've tried to build HEAD with Xcode 7.3.1 (Swift 2.x) and stumbled across multiple compiler errors inside `./Seeds/Curry/Source/Curry.swift` — this library has been already migrated to Swift 3.0 while `mas` isn't there yet (#33).

The problem is that in your Seedfile you don't pin `thoughtbot/Curry` dependency to any tag but use "master" (aka HEAD) reference instead. I suggest that you'll choose a correct tag that supports Swift 2.x (e.g. tag "v.2.2.0" works great for me) until `mas`’s codebase is upgraded properly.

--------

Thanks again for your work and have a great day!

**Comment by rodionovd** [comment]
Gosh, I always fail to figure out if there's already a PR for an issue I file! Turns out @tangestani has been already working on it here #38

**Comment by argon** [comment]
I just merged #38. Thanks for the heads-up as it had slipped under my radar.
