### ISSUE TITLE
Hang up when installing specific app

### ISSUE THREAD

**Issue by cybertk** [argon/mas#8]
**mas** hang up when installing **Install OS X El Capitan_10.11** with `mas install 1018109117`. Meanwhile, there's a dialog "Redownload Unavailable with This Apple ID" popped up with in MAS.

After close the dialog, **mas** exit with **Unknown error**.

<img width="419" alt="screen shot 2016-02-15 at 19 32 21" src="https://cloud.githubusercontent.com/assets/455809/13047552/dc47c284-d41a-11e5-83c0-dcb10c40dc87.png">

**Comment by argon** [comment]
Which app is 1018109117?

**Comment by cybertk** [comment]
@argon, it's **OS X El Capitan 10.11**

**Comment by argon** [comment]
Ah! I thought that was the version you were running! It's likely that OS X installers are treated differently by the underlying services. I'll try to do some investigation into this but I don't know when I will get time.

**Comment by cybertk** [comment]
I tried on OS X 10.10, which has not installed this App.  But still hang, see https://travis-ci.org/cybertk/vagrant-box-osx/builds/109337902

**Comment by timsutton** [comment]
For what it's worth, fetching OS X Yosemite worked fine for me on a 10.10 machine (similar to @cybertk I was also doing this for the purpose of automating an image build system). I haven't fully tested 10.11 yet, but a download at least _started_ successfully. The account I'm using has purchases for both the 10.10 and 10.11 installer apps, though.

**Comment by cybertk** [comment]
@timsutton  I'm doing the same thing, trying to automated `prepare_iso` and `packer build` in Travis CI. See https://github.com/cybertk/vagrant-box-osx/tree/ci

**Comment by timsutton** [comment]
@cybertk Do you get the same error on a local machine? Trying to download such a large file on a Travis CI worker seems like it might cause issues just due to the file size and length of time that would take to download.

**Comment by cybertk** [comment]
I was managed to download **OS X El Capitan** on Travis. Now I'm trying to find a way to pass the prepared ISO to packer's build cloud
