### ISSUE TITLE
Install Application by Name

### ISSUE THREAD

**Issue by jpscharf** [argon/mas#9]
Would it be possible to add the ability to search and install by name, e.g. `mas search "Degrees Weather"` or `mas install "Degrees Weather"`

The application ID can be looked up using a URL call:

`https://itunes.apple.com/search?entity=macSoftware&term=OneDrive&attribute=allTrackTerm`

Which will return a JSON response with matches, including the  `trackId` which is the applications ID number.

Reference: http://www.apple.com/itunes/affiliates/resources/documentation/itunes-store-web-service-search-api.html

**Comment by cybertk** [comment]
+1

**Comment by natelandau** [comment]
+1

**Comment by argon** [comment]
Fixed in the latest version

**Comment by aristidesfl** [comment]
Hmm this doesn't seem to be working. Example:

```
$ mas install Spark
Invalid value for 'Argument<Array<Int>>(defaultValue: nil, usage: "app ID(s) to install")': Spark
```

Am I missing anything?

mas 1.3.1
Sierra 10.12.3

**Comment by califool** [comment]
can anyone explain what this error means to me?  ~ mas install OneTab
Invalid value for 'Argument<Array<Int>>(defaultValue: nil, usage: "app ID(s) to install", usageParameter: nil)': OneTab

**Comment by 0xdevalias** [comment]
> can anyone explain what this error means to me? ~ mas install OneTab
> Invalid value for 'Argument<Array>(defaultValue: nil, usage: "app ID(s) to install", usageParameter: nil)': OneTab

@califool I believe it means you can't `mas install` by name, only by app ID. You can however search for apps by name with `mas search`.

`mas help` is your friend.

```shell
⇒ mas version
1.8.6
```

```shell
⇒ mas help install
Install from the Mac App Store

(integer)
	app ID(s) to install

--force
	force reinstall
```

```shell
⇒ mas help search
Search for apps from the Mac App Store

(string)
	the app name to search

[--price]
	Show price of found apps
```
